import { v4 as uuid } from "uuid";

import {
  sofa1,
  sofa2,
  sofa3,
  sofa4,
  sofa5,
  chair1,
  chair2,
  chair3,
  chair4,
  chair5,
  sofa6,
  sofa7,
  bed1,
  bed2,
  bed3,
  table1,
  table2,
  table3,
} from "assets/productImages";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Bali 3 Seater Sofa In Blue Colour",
    price: 17022,
    mrp: 35999,
    category: "sofa",
    rating: 4.5,
    brandName: "Trevi Furniture",
    discount: 53,
    image: sofa1,
    shipsIn: 2,
  },
  {
    _id: uuid(),
    title: "Niki 3 Seater Sofa In Yellow Colour",
    price: 6999,
    mrp: 8999,
    category: "sofa",
    rating: 4,
    brandName: "Springtek",
    discount: 22,
    image: sofa2,
    shipsIn: 3,
  },
  {
    _id: uuid(),
    title: "Florida Neo Sofa Cum Bed In Sky Blue Colour",
    price: 12925,
    mrp: 17000,
    category: "sofa",
    rating: 4.5,
    brandName: "Seventh Heaven",
    discount: 36,
    image: sofa3,
    shipsIn: 4,
  },
  {
    _id: uuid(),
    title: "Darwin 3 Seater Sofa in Blue Colour",
    price: 49494,
    mrp: 72999,
    category: "sofa",
    rating: 5,
    brandName: "Urban Living",
    discount: 32,
    image: sofa4,
    shipsIn: 4,
  },
  {
    _id: uuid(),
    title: "Snoozer Three Seater Sofa In Omega Grey Colour",
    price: 15666,
    mrp: 23200,
    category: "sofa",
    rating: 1.5,
    brandName: "Wakefit",
    discount: 32,
    image: sofa5,
    shipsIn: 4,
  },

  {
    _id: uuid(),
    title: "Cristobal 3 Seater Sofa In Buff Colour",
    price: 1899,
    mrp: 3499,
    category: "sofa",
    rating: 2.5,
    brandName: "Hosta Homes",
    discount: 46,
    image: sofa7,
    shipsIn: 3,
  },
  {
    _id: uuid(),
    title: "Cream Traditional Jaacquard Velvet 5 Seater Sofa",
    price: 1899,
    mrp: 3499,
    category: "sofa",
    rating: 1.5,
    brandName: "Hosta Homes",
    discount: 46,
    image: sofa6,
    shipsIn: 3,
  },

  {
    _id: uuid(),
    title: "Iconic Chair In Multi Colour",
    price: 4749,
    mrp: 7999,
    category: "chair",
    rating: 3,
    brandName: "Urbancart",
    discount: 41,
    image: chair3,
    shipsIn: 2,
  },
  {
    _id: uuid(),
    title: "Pario Guest Chair in Blue Colour",
    price: 11358,
    mrp: 19999,
    category: "chair",
    rating: 5,
    brandName: "Furniturstation",
    discount: 43,
    image: chair4,
    shipsIn: 2,
  },
  {
    _id: uuid(),
    title: "Tauras High Back Mesh Chair in Black Colour",
    price: 7979,
    mrp: 12999,
    category: "chair",
    rating: 2,
    brandName: "CellBell",
    discount: 39,
    image: chair5,
    shipsIn: 2,
  },
  {
    _id: uuid(),
    title: "Style Ergonomic Chair in Black Colour",
    price: 3875,
    mrp: 8499,
    category: "chair",
    rating: 4.5,
    brandName: "VOF",
    discount: 54,
    image: chair1,
    shipsIn: 1,
  },
  {
    _id: uuid(),
    title: "Desire Fabric Office Executive Chair in Grey Colour",
    price: 3989,
    mrp: 9999,
    category: "chair",
    rating: 3,
    brandName: "CellBell",
    discount: 60,
    image: chair2,
    shipsIn: 4,
  },
  {
    _id: uuid(),
    title: "Dreamer Metallic Folding Bed in Black Colour",
    price: 4274,
    mrp: 5999,
    category: "beds",
    rating: 1.5,
    brandName: "Springtek",
    discount: 29,
    image: bed1,
    shipsIn: 4,
  },
  {
    _id: uuid(),
    title: "Alvis Single Bed in Glossy Maroon Finish",
    price: 8856,
    mrp: 17999,
    category: "beds",
    rating: 3,
    brandName: "Springtek",
    discount: 51,
    image: bed2,
    shipsIn: 4,
  },
  {
    _id: uuid(),
    title: "Ursa King Size Bed in Black Finish",
    price: 9810,
    mrp: 19900,
    category: "beds",
    rating: 4,
    brandName: "@homes",
    discount: 51,
    image: bed3,
    shipsIn: 4,
  },
  {
    _id: uuid(),
    title: "Liva Coffee Table In Dark Asia Wood Finish",
    price: 4821,
    mrp: 6128,
    category: "table",
    rating: 5,
    brandName: "@homes",
    discount: 21,
    image: table1,
    shipsIn: 2,
  },
  {
    _id: uuid(),
    title: "Kiosk Coffee Table In Frosty White Colour",
    price: 4549,
    mrp: 6358,
    category: "table",
    rating: 4,
    brandName: "Globia",
    discount: 28,
    image: table2,
    shipsIn: 2,
  },
  {
    _id: uuid(),
    title: "Colombia 4 Seater Dining Table in Wenge Finish",
    price: 4811,
    mrp: 6500,
    category: "table",
    rating: 4,
    brandName: "Nilkamal",
    discount: 26,
    image: table3,
    shipsIn: 2,
  },
];
